blank_issues_enabled: false
contact_links:
  - name: Humanoid Support
    url: https://t.me/HumanoidSupport
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://github.com/TeamHumanoid/
    about: Basic documentation for setting up.
