name: Buster
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "https://telegra.ph/file/d828c90f5ad83b14f058b.jpg"
          replace: "https://telegra.ph/file/d9f817901a2b1acc417c7.jpg"
      - name: Create Pull Request
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Initial commit'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: PhoenixError
          commit_user_email: shivanshrajput2241@gmail.com
